apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: tkgs-prod01                         #cluster name, user defined
  namespace: prod
spec:
  distribution:
    version: v1.20                             #Resolves to the latest v1.18 image
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-small                 #vmclass for control plane nodes
      storageClass: vc01cl01-t0compute
    workers:
      count: 1                                 #number of worker nodes
      class: best-effort-small                 #vmclass for worker nodes
      storageClass: vc01cl01-t0compute
